import { Translations } from "./langTypes";

export const enTranslations: Translations = {
  blockTitles: {
    whatYouGet: "What you get",
    services: "Services",
    values: "Values",
    process: "Process",
    features: "Features",
    questionTitle1: "Stop Blending In",
    questionTitle2: "Start Standing Out",
    questionTitle3: "Does this apply to your business?",
    realTitle1: "Real Businesses",
    realTitle2: "Real Results",
    inspired: "Inspired",
    aboutMe: "About Me",
    work: "Work",
    contact: "Contact",
    reviews: "Reviews",
    blog: "Blog",
  },
  buttons: {
    workWithMe: "Work with me",
    view: "View",
    contact: "Contact",
    send: "Send",
    buildSign: "Let's Build Your Sign",
    buildBrand: "Let’s Build Your Brand",
  },
  form: {
    general: {
      firstName: "First Name",
      firstNamePlaceholder: "Joe",
      lastName: "Last Name",
      lastNamePlaceholder: "Smith",
      email: "Email",
      emailPlaceholder: "example@example.com",
      requiredAlert: "Please fill out all required fields",
      emailSent: "Email sent successfully",
      emailNotSent: "Email not sent",
      additionalInfo: "Additional Information",
      details: "Details",
      detailsPlaceholder: "I need a cool sign for my business...",
      referanceImage: "Image de référence",
      upload: "Télécharger des images",
    },
    cart: {
      province: "Province",
      city: "Ville",
      postalCode: "Code postal",
      postalCodePlaceholder: "A1A 1A1",
      delivery: "Méthode de livraison",
      addressLine: "Adresse",
    },
    flash: {
      bodyPosition: "Position du corps",
      bodyPositionPlaceholder: "Je voudrais une le long de ma jambe...",
      selectedFlash: "Flash sélectionné",
    },
    wood: {
      currency: "CAD",
      height: "Height",
      width: "Width",
      budget: "Budget",
      unit: "Inches",
    },
  },
  nav: {
    home: "Home",
    about: "About+Work",
    services: "Services",
  },
  other: {
    startAt: "Starting at",
  },
};
