import { Translations } from "./langTypes";

export const enTranslations: Translations = {
  titles: {
    whatYouGet: "What you get",
    services: "Services",
    process: "Process",
    questionTitle1: "Stop Blending In",
    questionTitle2: "Start Standing Out",
    questionTitle3: "Does this apply to your business?",
    realTitle1: "Real Businesses",
    realTitle2: "Real Results",
    quote: "Organized x Chaos",
    explore: "Explore my Work",
  },
  buttons: {
    workWithMe: "Work with me",
    view: "View",
    contact: "Let’s Talk",
    send: "Send",
    getQuote: "Get Your Quote",
    buildSign: "Let's Build Your Sign",
    buildBrand: "Let’s Build Your Brand",
    design: "Let’s Design",
    viewInstagram: "View my Insta",
    viewMyWork: "View my work",
    viewService: "View Service",
  },
  form: {
    general: {
      select: "Select",
      service: "Service",
      servicePlaceholder: "Select a service",
      firstName: "First Name",
      firstNamePlaceholder: "Joe",
      lastName: "Last Name",
      lastNamePlaceholder: "Smith",
      email: "Email",
      emailPlaceholder: "example@example.com",
      requiredAlert: "Please fill out all required fields",
      emailSent: "Email sent successfully",
      emailNotSent: "Email not sent",
      additionalInfo: "Additional Information",
      details: "Details",
      detailsPlaceholder: "I am looking for...",
      referanceImage: "Image de référence",
      upload: "Télécharger des images",
    },

    wood: {
      currency: "CAD",
      height: "Height",
      width: "Width",
      budget: "Budget",
      unit: "Inches",
    },
  },
  nav: {
    home: "Home",
    about: "About + Work",
    branding: "Branding",
    web: "Website",
    digital: "Design Services",
    wood: "Custom Signs",
  },
  work: {
    wood: "Signs",
    branding: "Branding",
    web: "Web Design",
    cards: "Cards",
    gallery: "Gallery",
  },
};
