// src/langs/en.ts
import { Translations } from "./langTypes";

export const enTranslations: Translations = {
  titles: {
    whatYouGet: "What you get",
    services: "Services",
    process: "Process",
    questionTitle1: "Stop Blending In",
    questionTitle2: "Start Standing Out",
    questionTitle3: "Does this apply to your business?",
    realTitle1: "Real Businesses",
    realTitle2: "Real Results",
    quote: "Organized x Chaos",
    explore: "Explore my Work",
  },
  buttons: {
    workWithMe: "Work With Me",
    view: "View",
    contact: "Let’s Chat",
    send: "Send",
    getQuote: "Get Your Quote",
    buildSign: "Build Your Sign",
    buildBrand: "Build Your Brand",
    design: "Let’s Design",
    viewInstagram: "View My Insta",
    viewMyWork: "View My Work",
    viewService: "View Service",
    viewCaseStudy: "View Case Study",
  },
  form: {
    general: {
      select: "Select",
      service: "Service",
      servicePlaceholder: "Select a service",
      firstName: "First Name",
      firstNamePlaceholder: "Joe",
      lastName: "Last Name",
      lastNamePlaceholder: "Smith",
      email: "Email",
      emailPlaceholder: "example@example.com",
      requiredAlert: "Hey, fill out all the required stuff!",
      emailSent: "Email sent successfully",
      emailNotSent: "Email not sent",
      additionalInfo: "Additional Information",
      details: "Project Info",
      detailsPlaceholder: "I am looking for...",
      referanceImage: "Reference Image",
      upload: "Upload Images",
    },
    wood: {
      currency: "$ CAD",
      height: "Height",
      width: "Width",
      budget: "Budget",
      unit: "Inches",
    },
  },
  nav: {
    home: "Home",
    services: "Services",
    signs: "Signs",
    decor: "Decor",
    work: "Work",
    about: "About",
  },
  work: {
    signs: "Signs",
    decor: "Decor",
  },
};
