import { Translations } from "./langTypes";

export const frTranslations: Translations = {
  titles: {
    whatYouGet: "Ce que vous obtenez",
    services: "Services",
    process: "Processus",
    questionTitle1: "Arrête de te fondre",
    questionTitle2: "Commencez à vous démarquer",
    questionTitle3: "Ça marche pour ton business ?",
    realTitle1: "Entreprises réelles",
    realTitle2: "Résultats réels",
    quote: "Organisé x Chaos",
    explore: "Explorez mon travail",
  },
  buttons: {
    workWithMe: "Bossons ensemble",
    view: "Voir",
    contact: "On jase ?",
    send: "Envoyer",
    getQuote: "Obtenez votre devis",
    buildSign: "Crée ton enseigne",
    buildBrand: "Crée ta marque",
    design: "Design ton projet",
    viewInstagram: "Check mon Insta",
    viewMyWork: "Voir mon travail",
    viewService: "Voir le service",
    viewCaseStudy: "Voir l'étude de cas",
  },
  form: {
    general: {
      select: "Sélectionner",
      service: "Service",
      servicePlaceholder: "Sélectionner un service",
      firstName: "Prénom",
      firstNamePlaceholder: "Joe",
      lastName: "Nom de famille",
      lastNamePlaceholder: "Smith",
      email: "Courriel",
      emailPlaceholder: "exemple@exemple.com",
      requiredAlert: "Hé, remplis tout le stock requis !",
      emailSent: "Email envoyé avec succès",
      emailNotSent: "Email non envoyé",
      additionalInfo: "Informations supplémentaires",
      details: "Infos du projet",
      detailsPlaceholder: "Décris ton projet",
      referanceImage: "Image de référence",
      upload: "Télécharger des images",
    },

    wood: {
      currency: "$ CAD",
      height: "Hauteur",
      width: "Largeur",
      budget: "Budget",
      unit: "Pouces",
    },
  },
  nav: {
    home: "Accueil",
    about: "À propos + Travail",
    branding: "Marque",
    web: "Design Web",
    digital: "Numérique",
    wood: "Enseignes",
  },
  work: {
    wood: "Enseignes",
    branding: "Marque",
    web: "Site Web",
    cards: "Cartes",
    gallery: "Galerie",
  },
};
