import { Translations } from "./langTypes";

export const frTranslations: Translations = {
  titles: {
    whatYouGet: "Ce que vous obtenez",
    services: "Services",
    process: "Processus",
    questionTitle1: "Arrêtez de vous fondre dans la masse",
    questionTitle2: "Commencez à vous démarquer",
    questionTitle3: "Est-ce que cela s'applique à votre entreprise?",
    realTitle1: "Entreprises reelles",
    realTitle2: "Résultats réels",
    quote: "Organisé x Chaos",
  },
  buttons: {
    workWithMe: "Travail avec moi",
    view: "Voir",
    contact: "Contact",
    send: "Envoyer",
    getQuote: "Obtenez votre devis",
    buildSign: "Faites votre signe",
    buildBrand: "Faites votre marque",
    viewInstagram: "Voir mon Insta",
    viewMyWork: "Voir mon travail",
  },
  form: {
    general: {
      select: "Sélectionner",
      service: "Service",
      servicePlaceholder: "Sélectionner un service",
      firstName: "Prénom",
      firstNamePlaceholder: "Joe",
      lastName: "Nom de famille",
      lastNamePlaceholder: "Smith",
      email: "Email",
      emailPlaceholder: "exemple@exemple.com",
      requiredAlert: "Veuillez remplir tous les champs obligatoires",
      emailSent: "Email envoyé avec succès",
      emailNotSent: "Email non envoyé",
      additionalInfo: "Informations supplémentaires",
      details: "Informations pertinentes",
      detailsPlaceholder: "Description du projet",
      referanceImage: "Image de référence",
      upload: "Télécharger des images",
    },

    wood: {
      currency: "CAD",
      height: "Hauteur",
      width: "Largeur",
      budget: "Budget",
      unit: "pouces",
    },
  },
  nav: {
    home: "Accueil",
    about: "À propos+Travail",
    branding: "Marque",
    web: "Design Web",
    digital: "Numérique",
    wood: "Bois",
  },
  work: {
    wood: "Bois",
    branding: "Marque",
    web: "Site Web",
    cards: "Cartes",
    gallery: "Galerie",
  },
};
