import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import styles from "./layout.module.scss";
import { Navbar } from "@/components/navbar/Navbar/Navbar";
import "@/styles/Main.css";
import "@/styles/ScrollBar.scss";
import "@/styles/index.scss";
import { NextIntlClientProvider } from "next-intl";
import { Footer } from "@/components/footer/Footer";
import { IFooter, INavBar } from "@/data.d";
import { useFetchPage } from "../api/useFetchPage";
import { LangType } from "@/i18n";

const inter = Inter({ subsets: ["latin"] });

// FIX: Chnage the metadata to the correct values for each page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: LangType };
}>) {
  const navbarQuery = `*[_type == 'navbar' && lang == '${locale}'][0]`;
  const footerQuery = `*[_type == 'footer' && lang == '${locale}'][0]{
      ...,
      legals[]->{
        title,
        path,
      },
      socials->{
        ...,
        links[],
      },
    }`;
  const navbarData: INavBar = await useFetchPage(navbarQuery, "navbar");
  const footerData: IFooter = await useFetchPage(footerQuery, "footer");
  return (
    <html lang={locale}>
      <NextIntlClientProvider locale={locale}>
        <head>
          <meta name="theme-color" content="#fec301" />
          <meta name="version" content="%NEXT_PUBLIC_VERSION%" />
        </head>
        <body className={inter.className}>
          <div id="root">
            <div className={styles.app}>
              <Navbar {...navbarData} />
              <div className={styles.page}>{children}</div>
              <Footer
                legals={footerData?.legals}
                trademark={footerData?.trademark}
                links={navbarData?.links}
                socials={{ links: footerData?.socials?.links }}
              />
            </div>
          </div>
        </body>
        <GoogleAnalytics gaId="GTM-T7H3RP3Q" />
        {/* FIX: Make sure to test google Analistics */}
      </NextIntlClientProvider>
    </html>
  );
}
